keys:
  - &judahf_personal age1atspa66spctj4w93knzvt7f8llu9fydy5xg9dgfd673d9qvrz3rs7nt5gy
creation_rules:
  - path_regex: secrets/[^/]+(\.(yaml|json|env|ini))?$
    key_groups:
      - age:
          - *judahf_personal
