# Do not modify this file! It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations. Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = [
        "xhci_pci"
        "ahci"
        "nvme"
        "usbhid"
        "uas"
        "sd_mod"
      ];
      kernelModules = [ ];
      luks.devices."luks-b62c8c23-d723-41b6-b1bd-e223180d3ecf".device =
        "/dev/disk/by-uuid/b62c8c23-d723-41b6-b1bd-e223180d3ecf";
    };

    kernelModules = [ ];
    extraModulePackages = [ ];
  };

  fileSystems = {
    "/" = {
      device = "/dev/mapper/luks-b62c8c23-d723-41b6-b1bd-e223180d3ecf";
      fsType = "ext4";
    };

    "/boot" = {
      device = "/dev/disk/by-uuid/CFE3-4028";
      fsType = "vfat";
      options = [
        "fmask=0077"
        "dmask=0077"
      ];
    };
  };

  swapDevices = [
    { device = "/dev/mapper/luks-5ec64ea0-e292-43f9-9dfe-99d6ea33642d"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
