#export GOPATH=$HOME/go
#export PATH=$PATH:$GOROOT/bin:$GOPATH/bin

export SSH_AUTH_SOCK=/Users/judahfuller/Library/Group\ Containers/2BUA8C4S2C.com.1password/t/agent.sock

export PATH="$HOME/.cargo/bin:$PATH"
export PNPM_HOME="$HOME/.pnpm/"
export PATH="$HOME/.pnpm/:$PATH"
export PATH="/Applications/Ghostty.app/Contents/MacOS:/Users/judahfuller/Library/Python/3.9/bin:$PATH"

export ANTHROPIC_BASE_URL="https://openrouter.ai/api"
export ANTHROPIC_AUTH_TOKEN="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"
export ANTHROPIC_API_KEY="" # Important: Must be explicitly empty

# bun completions
[ -s "$HOME/.bun/_bun" ] && source "$HOME/.bun/_bun"

# Nix
export PATH=/run/current-system/sw/bin:$HOME/.nix-profile/bin:$PATH
if [ -e '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh' ]; then
. '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh'
fi

eval "$(fnm env --use-on-cd --shell zsh)"

eval "$(starship init zsh)"
eval "$(zoxide init zsh)"

fastfetch
