{ ... }: {
  imports = [
    ./flake
    ./browsers
    ./communication
    ./darwin
    ./design
    ./desktop
    ./dev
    ./fonts
    ./gaming
    ./home
    ./libraries
    ./media
    ./nix-config
    ./networking
    ./nixos
    ./productivity
    ./production
    ./secrets
    ./security
    ./shell
    ./utilities
    ./users
    ./hosts/darwin/gale
    ./hosts/nixos/clawdbot
    ./hosts/nixos/gitlab
    ./hosts/nixos/jfpi
    ./hosts/nixos/popper
    ./hosts/nixos/zevlor
  ];
}
